export interface DataPoint {
  ind: string;
  dat: string;
  chrom: string;
  anc: string;
  hap: number;
  len_mea: number;
  len_med: number;
  len_max: number;
  len_min: number;
  nfr: number;
  seq: number;
  sex: string;
  pop: string;
  reg: string;
  phase_state: string;
  mpp: number;
  lat: number;
  lon: number;
  jitteredLat?: number;
  jitteredLon?: number;
  ind_phase: string;
  ancAMR: number | null;
  ancEAS: number | null;
  ancSAS: number | null;
  ancAFR: number | null;
  ancEUR: number | null;
  ancOCE: number | null;
  ancOCE2: number | null;
  ancMID: number | null;
}
